/* Crown & Ash — five fall storefront options.
   Prices = approximate 2026 retail before tax; Michaels / Hobby Lobby assume
   their routine 40–50% seasonal sales. Verify at purchase. */
window.C4M_OPTIONS = [
  {
    key: 'A', name: 'The Humidor', tier: 'Signature',
    line: 'Oxblood, bronze and aged brass. Feels like a private cigar club.',
    palette: [['#5a1a1f','Oxblood'],['#8a3b2a','Burnt sienna'],['#b0813f','Aged brass'],['#1c1714','Humidor black'],['#e7dccb','Parchment']],
    rug: 'A 5×7 oxblood-and-charcoal vintage-medallion flatweave laid over a larger black-and-natural jute. Its colors set the palette for the mums and pumpkins.',
    mums: 'Burgundy and bronze mums, packed three to a tier',
    plan: { rug:'#5a1a1f', rug2:'#2a2420', planter:'#1c1714', stand:'#8a3b2a', accent:'#b0813f' },
    items: [
      ['Target','Outdoor medallion rug, 5×7 (Threshold)',1,69],
      ['Walmart','Black & natural jute-look outdoor rug, 6×9 (layer)',1,45],
      ['Hobby Lobby','Tall black metal urn planters (sale)',2,70],
      ['Hobby Lobby','3-tier black iron plant stands (sale)',2,70],
      ['Walmart / Lowe\u2019s','Live mums, 9″ — burgundy + bronze',10,90],
      ['Michaels','Faux pumpkins, cinderella + heirloom mix (sale)',6,42],
      ['Target','Black metal LED lanterns, large',2,50],
      ['Michaels','Wine velvet ribbon + faux magnolia stems',1,24],
      ['Lowe\u2019s','Pea gravel (ballast) + outdoor rug tape',1,18],
    ],
  },
  {
    key: 'B', name: 'Gold Leaf', tier: 'Classic',
    line: 'Black, ivory and gold, like a cigar band. The closest match to the lounge\u2019s look.',
    palette: [['#121110','Onyx'],['#f1ead9','Ivory'],['#c9a24e','Gold leaf'],['#d9a53a','Harvest gold'],['#6f5a3a','Tobacco']],
    rug: 'A black-and-ivory striped flatweave over natural jute. Crisp and formal, so gold mums stand out against it.',
    mums: 'Golden-yellow and ivory mums, with gold-leaf faux pumpkins',
    plan: { rug:'#121110', rug2:'#cbb88f', planter:'#121110', stand:'#c9a24e', accent:'#d9a53a' },
    items: [
      ['Target','Black & ivory striped outdoor rug, 4×6',1,45],
      ['Walmart','Natural jute-look outdoor rug, 5×8 (layer)',1,35],
      ['Walmart','Black fluted resin urns, 16″ (Better Homes & Gardens)',2,50],
      ['Hobby Lobby','Black metal plant stands, gold accents (sale)',2,60],
      ['Walmart / Lowe\u2019s','Live mums, 9″ — gold + ivory',10,90],
      ['Dollar General','White & cream faux pumpkins',6,30],
      ['Michaels','Gold leaf metallic paint (paint pumpkin stems/tops)',1,8],
      ['Dollar General','LED pillar candles for lanterns',4,16],
      ['Hobby Lobby','Black & gold lanterns (sale)',2,40],
      ['Lowe\u2019s','Pea gravel + rug tape',1,18],
    ],
  },
  {
    key: 'C', name: 'Cognac Leather', tier: 'Warm',
    line: 'Whiskey, saddle leather and cream. Warm and inviting, like a leather armchair.',
    palette: [['#7a4424','Cognac'],['#b3692e','Whiskey'],['#d88a3a','Amber'],['#efe3cd','Cream'],['#3b2a1f','Saddle']],
    rug: 'A rust-and-cream Persian-style washable flatweave. Its warm pattern ties in with the brick.',
    mums: 'Orange and rust mums, with cream heirloom pumpkins and wheat',
    plan: { rug:'#7a4424', rug2:'#efe3cd', planter:'#3b2a1f', stand:'#b3692e', accent:'#d88a3a' },
    items: [
      ['Target','Rust Persian-style outdoor rug, 5×7',1,69],
      ['HomeGoods / Marshalls','Tall bronze or brown ceramic planters',2,80],
      ['Michaels','Wood crates, stacked as risers (sale)',4,40],
      ['Walmart / Lowe\u2019s','Live mums, 9″ — orange + rust',10,90],
      ['Michaels','Faux heirloom pumpkins, cream + peach (sale)',6,42],
      ['Michaels','Dried wheat bundles (kept away from ash urns)',2,20],
      ['Target','Wood & metal LED lanterns',2,50],
      ['Lowe\u2019s','Pea gravel + rug tape',1,18],
    ],
  },
  {
    key: 'D', name: 'Velvet Ember', tier: 'Statement',
    line: 'Plum, merlot and copper, with velvet pumpkins. The most eye-catching option.',
    palette: [['#3d1a3a','Aubergine'],['#6b2340','Merlot'],['#b86b3c','Copper'],['#1f2a33','Midnight'],['#e9dfd0','Linen']],
    rug: 'A navy-and-rust vintage-look runner, 2.5×8, running across the door threshold, with a round jute accent under each stand.',
    mums: 'Purple, burgundy and bronze mums, with velvet pumpkins',
    plan: { rug:'#1f2a33', rug2:'#b86b3c', planter:'#1c1714', stand:'#6b2340', accent:'#3d1a3a' },
    items: [
      ['Target','Navy & rust outdoor runner, 2.5×8',1,45],
      ['Walmart','Round jute-look outdoor mats, 3′',2,40],
      ['Hobby Lobby','Tall black & copper planters (sale)',2,80],
      ['Hobby Lobby','3-tier iron plant stands (sale)',2,70],
      ['Walmart / Lowe\u2019s','Live mums, 9″ — purple, burgundy, bronze',12,108],
      ['Hobby Lobby','Velvet pumpkins, plum + rust (sale)',6,36],
      ['Michaels','Faux ornamental kale + berry picks (sale)',6,30],
      ['Target','Copper LED lanterns',2,60],
      ['Lowe\u2019s','Pea gravel + rug tape',1,18],
    ],
  },
  {
    key: 'E', name: 'Ash & Ivory', tier: 'Essential',
    line: 'Charcoal, ivory and a touch of burgundy. The most affordable option, still clean and upscale.',
    palette: [['#2b2a28','Charcoal'],['#6e6a64','Ash'],['#f0ebe1','Ivory'],['#5e1d24','Burgundy'],['#a88a5c','Tobacco']],
    rug: 'A charcoal-and-ivory diamond outdoor rug. Its simple pattern lets the white and burgundy mums take the focus.',
    mums: 'White mums with a pair of burgundy accents',
    plan: { rug:'#2b2a28', rug2:'#f0ebe1', planter:'#2b2a28', stand:'#6e6a64', accent:'#5e1d24' },
    items: [
      ['Walmart','Charcoal & ivory outdoor rug, 4×6 (Mainstays)',1,30],
      ['Dollar General','Large charcoal resin planters',2,30],
      ['Walmart','Black metal 3-tier plant stands',2,50],
      ['Walmart / Lowe\u2019s','Live mums, 9″ — white + burgundy',8,64],
      ['Dollar General','White faux pumpkins',5,25],
      ['Dollar General','LED candles + glass hurricane jars',2,20],
      ['Lowe\u2019s','Pea gravel + rug tape',1,18],
    ],
  },
];
